mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from polls import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include(urls))
]

polls/urls.py
from django.contrib import admin
from django.urls import path
from . import views
import polls

app_name = 'polls'

urlpatterns = [
    
    path('index/', views.index, name='index'),
    
    path('person/<int:person_id>/', views.show_specific_person, name='show_specific_person'),
    
    path('todo_list/<int:todo_id>/', views.show_specific_todo_list, name='show_specific_todo_list'),

]

polls/models.py
from django.db import models
from datetime import datetime

from django.db.models.deletion import CASCADE

# Create your models here.

class Person(models.Model):
    person_name = models.CharField(max_length=100)
    person_DOB = models.DateField(blank=True)
    person_address = models.TextField(blank=True)

    def __str__(self):
        return self.person_name


class ToDoList(models.Model):
    list_name = models.CharField(max_length=100)
    owner = models.ForeignKey(Person, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.list_name}"


class Task(models.Model):
    task_title = models.CharField(max_length=100, blank=False, unique=True)
    start_time = models.DateTimeField(default=datetime.now())
    is_complete = models.BooleanField(default=False)
    end_time = models.DateTimeField(blank=True)
    task_list = models.ForeignKey(ToDoList, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.task_title}"

polls/views.py
from django.http.response import Http404, HttpResponse
from django.shortcuts import render
from .models import ToDoList, Person, Task
# Create your views here.

def get_person(person_id):
    try:
        obj = Person.objects.get(pk=person_id)
        return obj
    except Person.DoesNotExist:
        raise Http404("Person Does Not Exits.")

def get_todo_task(todo_id):
    try:
        obj = ToDoList.objects.get(pk=todo_id)
        return obj
    except ToDoList.DoesNotExist:
        raise Http404("List not Found")

def index(request):

    person_list = Person.objects.all()
    persons_dictonary = {'person_list': person_list}
    return render(request, 'polls/index.html', persons_dictonary)


def show_specific_person(request, person_id):


    required_list = [todo_list for todo_list in ToDoList.objects.all(
    ) if todo_list.owner.id == person_id]
    return render(request, 'polls/todo_list.html', {
        'list_detail': required_list,
        'owner': get_person(person_id)
        })


def show_specific_todo_list(request, todo_id):

    task_details = [task_list for task_list in Task.objects.all(
    ) if task_list.task_list.id == todo_id]

    return render(request, 'polls/task_list.html', 
                  {"task_list": task_details,
                   'task_name': get_todo_task(todo_id)})

polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div>
        <h2>Welcome to our System</h2>
        <h3>Please Click on your respective name</h3>

        <b><p>Name of Person</p></b>
        <ul>

        {% for person in person_list %}

            <li> <a href= "{% url 'polls:show_specific_person' person.id %}">{{ person.person_name }} </a> </li>
            
        {% endfor %}

        </ul>
    </div>
</body>
</html>

polls/templates/polls/task_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>{{task_name}}</h1>

    <ul>
        {% for task in task_list %}
           <li> {{ task }} </li>
        {% endfor %}
        
    </ul>

</body>
</html>

polls/templates/polls/todo_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Welcome {{ owner }}    </h1>


    <ul>
    {% for todo_list in list_detail %}
        <li> <a href= " {% url 'polls:show_specific_todo_list' todo_list.id %}">{{todo_list}} </a> </li>
    
    {% endfor %}

    </ul>
    
</body>
</html>